version: '3'
services:
  tsbackend:
    container_name: tsbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
    command: npm run dev
      
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodbdata:
